# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc28adcbec61b5b4e765fb1e8ed2fc1d73865e1d62612d6d511ee27086ac44bae336d28e211cc6e903bda51f5623d2bceee42c93ac9770824dfca5ac0750288

test:
  secret_key_base: fedeff7d52073005db9c9c51626dfa439a78060647552017d3f300a9ccb57c3ada21204bb6f1a7bdd2c770e2a95e2e46c737f4259b15c9cf50364a647ea61a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
